#!/bin/bash

echo ' __ _          __  __ '
echo '/ _\ |_ _   _ / _|/ _|'
echo '\ \| __| | | | |_| |_ '
echo '_\ \ |_| |_| |  _|  _|'
echo '\__/\__|\__,_|_| |_|  '
echo ''

echo "> Starting installation process"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

ROOT=`pwd`

source scripts/runnable/packages
source scripts/runnable/symlinks
source scripts/runnable/post

# TODO
# git reset HEAD vundle
# git submodule update
# https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# https://linux.dropbox.com/packages/ubuntu/dropbox_1.4.0_amd64.deb
#
# sudo add-apt-repository ppa:tiheum/equinox
# sudo apt-get update
# sudo apt-get install faenza-icon-theme

# git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
# git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
#
# I need a way to install my default/useful/favorite rubygems in default gemset automaticaly
# pry, pry-doc
# logger, logger-colors
# rails
# rspec, cucumber
# mechanize
# boom
# hub
