#!/usr/bin/env bash

echo '> Installing packages'

sudo apt-get -yqq install \
gmrun \
curl \
htop \
zsh \
vim  \
tint2 \
openbox \
xcompmgr \
mpg123 \
aptitude \
thunar \
ttf-droid \
ttf-inconsolata \
vim-gtk \
ack-grep \
terminator \
python-fontforge \
wmctrl \
xclip \
ffmpeg \
libgconf-2-4 \
libnss3-1d \
libxss1 \
ncurses-term \
lib32stdc++6 \
lib32asound2 \
ia32-libs \
libc6-i386 \
lib32gcc1 \
gtk-theme-switch \
nitrogen \
scrot \
gtk2-engines-pixbuf \
libc6-dev \
libmysql++-dev \
libsqlite3-dev \
make \
build-essential \
libssl-dev \
libreadline6-dev \
zlib1g-dev \
libyaml-dev \
autoconf \
