#!/bin/bash

echo '> Some post-installation magic'

echo '> Changing shell to zsh'
chsh -s $(which zsh)

echo '> Installing oh-my-zsh'
curl -Ls https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
