#!/bin/bash

if [ -z "${ROOT}" ]; then ROOT="${PWD}/../.."; fi

echo '> Applying symlinks'
echo ''

mkdir ~/.config > /dev/null 2>&1

unlink ~/.Xdefaults
echo '  xdefaults:  x/xdefaults => ~/.Xdefaults'
ln -sf $ROOT/x/xdefaults ~/.Xdefaults

unlink ~/.zshrc
echo '  zsh:        zsh/zshrc => ~/.zshrc'
ln -sf $ROOT/zsh/zshrc ~/.zshrc

unlink ~/.bash_profile
echo '  profile:    zsh/bash_profile => ~/.bash_profile'
ln -sf $ROOT/zsh/bash_profile ~/.bash_profile

echo '  git:        git/gitconfig => ~/.gitconfig'
ln -sf $ROOT/git/gitconfig ~/.gitconfig

echo '  vimrc:      vim/vimrc => ~/.vimrc'
ln -sf $ROOT/vim/vimrc ~/.vimrc

unlink ~/.vim
echo '  vim:        vim/vimfiles => ~/.vim'
ln -sf $ROOT/vim/vimfiles ~/.vim

unlink ~/.resources 
echo '  resources:  resources => ~/.resources'
ln -sf $ROOT/resources ~/.resources

unlink ~/.config/openbox
echo '  openbox:    openbox => ~/.config/openbox'
ln -sf $ROOT/openbox ~/.config/openbox

unlink ~/.config/tint2
echo '  tint2:      tint2 => ~/.config/tint2'
ln -sf $ROOT/tint2 ~/.config/tint2

unlink ~/.config/terminator
echo '  terminator: terminator => ~/.config/terminator'
ln -sf $ROOT/terminator ~/.config/terminator

unlink ~/.config/awesome
echo '  awesome:    awesome => ~/.config/awesome'
ln -sf $ROOT/awesome ~/.config/awesome

echo ''
