#!/usr/bin/env bash

e_arrow 'Installing packages'

sudo apt-get -qq install \
gmrun \
curl \
htop \
zsh \
vim  \
tint2 \
openbox \
xcompmgr \
mpg123 \
aptitude \
thunar \
ttf-droid \
ttf-inconsolata \
vim-gtk \
ack-grep \
terminator \
python-fontforge \
wmctrl \
xclip \
ffmpeg \
libnss3-1d \
libxss1 \
ncurses-term \
gtk-theme-switch \
nitrogen \
scrot \
gtk2-engines-pixbuf \
libc6-dev \
libmysql++-dev \
libsqlite3-dev \
make \
build-essential \
libssl-dev \
libreadline6-dev \
zlib1g-dev \
libyaml-dev \
autoconf \
tree \
