#!/usr/bin/env bash

e_arrow 'Some post-installation magic'

#===========================================================
# 1.                     ZSH
#===========================================================
if [[ $SHELL =~ zsh ]]; then
  e_success 'You already use zsh. Awesome!'
else
  e_arrow 'Changing shell to zsh'
  sudo chsh -s $(which zsh)
fi


#===========================================================
# 2.                     VUNDLE
#===========================================================
if [ -d "$HOME/.vim/bundle/vundle" ]; then
  e_already 'vundle'
else
  e_arrow 'Installing vundle'
  mkdir ~/.vim/bundle/vundle -p
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi


#===========================================================
# 3.                     RBENV
#===========================================================
if [ -d "$HOME/.rbenv" ]; then
  e_already 'rbenv'
else
  e_arrow 'Installing rbenv'
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  cd ~/.rbenv/plugins/ruby-build
  ./install.sh
  sudo chown madundead:madundead ~/.rbenv -R
fi


#===========================================================
# 3.                     OH-MY-ZSH
#===========================================================
if [ -d "$HOME/.oh-my-zsh" ]; then
  e_already 'oh-my-zsh'
else
  e_arrow 'Installing oh-my-zsh'
  curl -Ls https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh > /dev/null 2>&1
fi


# TODO: MAKE IT WORK
#===========================================================
# 4.                     PYTHON SHIT
#===========================================================
# e_arrow 'Installing pip'
# curl -s https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python > /dev/null 2>&1


#===========================================================
# 5.                     FONTS
#===========================================================
e_arrow 'Installing fonts'
sudo mkdir /usr/share/fonts/truetype/custom -p > /dev/null 2>&1
sudo cp resources/fonts/Monaco_Linux-Powerline.ttf /usr/share/fonts/truetype/custom/
e_arrow 'Rebuilding fonts cache'
sudo fc-cache -f
