ZSH=$HOME/.oh-my-zsh
SECRETS=$HOME/Dropbox/Backup/credentials.sh

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"

# Env
export EDITOR="vim"

# Aliases
alias be="bundle exec"
alias dspace="df -h -T"
alias v="vim"
alias imgur="~/Development/madundead/stuff/scripts/bin/imgur"
alias mountiso="~/Development/madundead/stuff/scripts/bin/mountiso"
alias dev="cd ~/Development"
alias stuff="cd ~/Development/madundead/stuff"
alias mashup="cd ~/Development/madundead/mashup"
alias fugu="cd ~/Development/madundead/fugu"

# Settings
setopt autocd

# Plugins
plugins=(git nyan)

source $SECRETS
source $ZSH/oh-my-zsh.sh
unsetopt correct_all

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

# Customize to your needs...
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/madundead/.rvm/bin


# Shamelessly taken from here:
# https://github.com/paulmillr/dotfiles

# Show how much RAM application uses.
# $ ram safari
# # => safari uses 154.69 MBs of RAM.
function ram() {
  local sum
  local items
  local app="$1"
  if [ -z "$app" ]; then
    echo "First argument - pattern to grep from processes"
  else
    sum=0
    for i in `ps aux | grep -i "$app" | grep -v "grep" | awk '{print $6}'`; do
      sum=$(($i + $sum))
    done
    sum=$(echo "scale=2; $sum / 1024.0" | bc)
    if [[ $sum != "0" ]]; then
      echo "${fg[blue]}${app}${reset_color} uses ${fg[green]}${sum}${reset_color} MBs of RAM."
    else
      echo "There are no processes with pattern '${fg[blue]}${app}${reset_color}' are running."
    fi
  fi
}
