ZSH=$HOME/.oh-my-zsh
SECRETS=$HOME/Dropbox/backup/credentials.sh

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"

# Env
export EDITOR="vim"

# Aliases
alias be="bundle exec"
alias dspace="df -h -T"
alias v="vim"
alias imgur="~/Projects/stuff/scripts/bin/imgur"

# Settings
setopt autocd

# Plugins
plugins=(git nyan)

source $SECRETS
source $ZSH/oh-my-zsh.sh
unsetopt correct_all

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

# Customize to your needs...
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/madundead/.rvm/bin:/home/madundead/.rvm/bin
